apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lukato

commonLabels:
  app.kubernetes.io/name: lukato
  app.kubernetes.io/part-of: lukato
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - job-migrate.yaml
  # - servicemonitor.yaml   # habilite com Prometheus Operator
  # secret.example.yaml NAO entra aqui: use ExternalSecrets/Vault

images:
  - name: lukato
    newTag: "1.0.0"
