apiVersion: v1
kind: Namespace
metadata:
  name: lukato
  labels:
    app.kubernetes.io/name: lukato
    app.kubernetes.io/part-of: lukato
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
