"""Schemas da API v1: o contrato publico de entrada e saida de cada recurso.

Os schemas sao a fronteira entre o JSON do cliente e os DTOs da aplicacao. Cada
recurso tem um par `Request`/`Response` que **espelha** o modelo de dominio sem
expor campo interno — hash de senha, segredo de chave e vetor de embedding nunca
atravessam esta camada.

Convencoes:

* entrada herda de :class:`~lukato.interfaces.http.schemas.common.InSchema`
  (`extra="forbid"`) e traz `to_input()`/`to_domain()`;
* saida herda de :class:`~lukato.interfaces.http.schemas.common.OutSchema` e traz
  `from_domain()`/`from_result()`;
* toda lista viaja no envelope :class:`~lukato.interfaces.http.schemas.common.Page`.
"""

from __future__ import annotations

from lukato.interfaces.http.schemas.adwatch import (
    AdWatchEmbeddingsInfo,
    AdWatchMaxScoreWithout,
    AdWatchThresholds,
    AdWatchTopK,
    AdWatchWindowsInfo,
    BulkImportBody,
    BulkImportRequest,
    BulkImportResponse,
    CapabilitiesOut,
    CommercialCreate,
    CommercialDetailOut,
    CommercialOut,
    CommercialUpdate,
    DetectionEvidenceOut,
    DetectionOut,
    DetectionReportOut,
    DetectionReviewRequest,
    DetectRequest,
    FingerprintOut,
    ImportResultOut,
    IngestReportOut,
    IngestStepOut,
    MediaCreate,
    MediaOut,
    OcrImportRequest,
    OcrTextOut,
    SceneCutOut,
    SceneImportRequest,
    TranscriptImportRequest,
    TranscriptOut,
    TranscriptWordOut,
)
from lukato.interfaces.http.schemas.common import (
    DEFAULT_LIMIT,
    ERROR_RESPONSES,
    MAX_LIMIT,
    Acknowledged,
    ComponentHealth,
    DeletedResponse,
    ErrorBody,
    ErrorResponse,
    HealthStatus,
    InSchema,
    LivenessResponse,
    OutSchema,
    Page,
    PaginationParams,
    ProviderInfoOut,
    ProvidersResponse,
    ReadinessResponse,
    TokenUsageOut,
    error_responses,
)
from lukato.interfaces.http.schemas.finops import (
    BudgetCreate,
    BudgetOut,
    BudgetStatusOut,
    BudgetUpdate,
    CostPointOut,
    CostSeriesResponse,
    CostSummaryOut,
    ModelPriceIn,
    ModelPriceOut,
    PriceTableOut,
    PriceTableUpdate,
    TokenUsageIn,
    UsageCreate,
    UsageRecordOut,
)
from lukato.interfaces.http.schemas.guardrails import (
    GuardrailFindingOut,
    GuardrailRuleIn,
    GuardrailRuleOut,
    PolicyCreate,
    PolicyDraft,
    PolicyOut,
    PolicyTestRequest,
    PolicyTestResponse,
    PolicyUpdate,
    RuleKindInfo,
)
from lukato.interfaces.http.schemas.identity import (
    ApiKeyCreate,
    ApiKeyCreatedOut,
    ApiKeyOut,
    ChangePasswordRequest,
    LoginRequest,
    MeResponse,
    RefreshRequest,
    TokenResponse,
    UserCreate,
    UserOut,
    UserUpdate,
)
from lukato.interfaces.http.schemas.knowledge import (
    CollectionOut,
    DocumentCreate,
    DocumentOut,
    EmbeddingInfo,
    IngestResponse,
    KnowledgeHealthOut,
    SearchHitOut,
    SearchRequest,
    SearchResponse,
)
from lukato.interfaces.http.schemas.modules import (
    ChatMessageIn,
    ModuleBindingIn,
    ModuleBindingOut,
    ModuleCreate,
    ModuleInvokeRequest,
    ModuleInvokeResponse,
    ModuleOut,
    ModuleStatusUpdate,
    ModuleUpdate,
)
from lukato.interfaces.http.schemas.prompts import (
    PromptCloneRequest,
    PromptCreate,
    PromptOut,
    PromptPreviewRequest,
    PromptPreviewResponse,
    PromptUpdate,
)
from lukato.interfaces.http.schemas.runs import RunOut, RunStepOut, RunSummaryOut

__all__ = [
    "DEFAULT_LIMIT",
    "ERROR_RESPONSES",
    "MAX_LIMIT",
    "Acknowledged",
    "AdWatchEmbeddingsInfo",
    "AdWatchMaxScoreWithout",
    "AdWatchThresholds",
    "AdWatchTopK",
    "AdWatchWindowsInfo",
    "ApiKeyCreate",
    "ApiKeyCreatedOut",
    "ApiKeyOut",
    "BudgetCreate",
    "BudgetOut",
    "BudgetStatusOut",
    "BudgetUpdate",
    "BulkImportBody",
    "BulkImportRequest",
    "BulkImportResponse",
    "CapabilitiesOut",
    "ChangePasswordRequest",
    "ChatMessageIn",
    "CollectionOut",
    "CommercialCreate",
    "CommercialDetailOut",
    "CommercialOut",
    "CommercialUpdate",
    "ComponentHealth",
    "CostPointOut",
    "CostSeriesResponse",
    "CostSummaryOut",
    "DeletedResponse",
    "DetectRequest",
    "DetectionEvidenceOut",
    "DetectionOut",
    "DetectionReportOut",
    "DetectionReviewRequest",
    "DocumentCreate",
    "DocumentOut",
    "EmbeddingInfo",
    "ErrorBody",
    "ErrorResponse",
    "FingerprintOut",
    "GuardrailFindingOut",
    "GuardrailRuleIn",
    "GuardrailRuleOut",
    "HealthStatus",
    "ImportResultOut",
    "InSchema",
    "IngestReportOut",
    "IngestResponse",
    "IngestStepOut",
    "KnowledgeHealthOut",
    "LivenessResponse",
    "LoginRequest",
    "MeResponse",
    "MediaCreate",
    "MediaOut",
    "ModelPriceIn",
    "ModelPriceOut",
    "ModuleBindingIn",
    "ModuleBindingOut",
    "ModuleCreate",
    "ModuleInvokeRequest",
    "ModuleInvokeResponse",
    "ModuleOut",
    "ModuleStatusUpdate",
    "ModuleUpdate",
    "OcrImportRequest",
    "OcrTextOut",
    "OutSchema",
    "Page",
    "PaginationParams",
    "PolicyCreate",
    "PolicyDraft",
    "PolicyOut",
    "PolicyTestRequest",
    "PolicyTestResponse",
    "PolicyUpdate",
    "PriceTableOut",
    "PriceTableUpdate",
    "PromptCloneRequest",
    "PromptCreate",
    "PromptOut",
    "PromptPreviewRequest",
    "PromptPreviewResponse",
    "PromptUpdate",
    "ProviderInfoOut",
    "ProvidersResponse",
    "ReadinessResponse",
    "RefreshRequest",
    "RuleKindInfo",
    "RunOut",
    "RunStepOut",
    "RunSummaryOut",
    "SceneCutOut",
    "SceneImportRequest",
    "SearchHitOut",
    "SearchRequest",
    "SearchResponse",
    "TokenResponse",
    "TokenUsageIn",
    "TokenUsageOut",
    "TranscriptImportRequest",
    "TranscriptOut",
    "TranscriptWordOut",
    "UsageCreate",
    "UsageRecordOut",
    "UserCreate",
    "UserOut",
    "UserUpdate",
    "error_responses",
]
